In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
Quora_Question = pd.read_csv("train.csv")

In [3]:
sample = Quora_Question.sample(30000)

In [4]:
sample.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [10]:
sample.duplicated().sum()

np.int64(0)

In [12]:
quest_df = sample[['question1','question2']]
quest_df.head()

,question1,question2
204878,Does basketball or swimming increase height of...,Is it possible to Increase height or get talle...
65972,What are your views on Adhivakta Parishad?,How and where I can find freelance job of meta...
131332,Should you follow your CEO on Twitter?,Where can I get real active Instagram followers?
249555,Why does people have fears?,Why do people fear immigration?
101294,What's the best way to tell a friend they have...,How do you tell a friend she/he has a terrible...

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

# merge text
questions = list(quest_df['question1']) + list(quest_df['question2'])

cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [23]:
temp_df1 = pd.DataFrame(q1_arr,index=quest_df.index)
temp_df2 = pd.DataFrame(q2_arr,index=quest_df.index)
temp_df = pd.concat([temp_df1,temp_df2],axis=1)
temp_df.shape

(30000, 6000)

In [24]:
temp_df['is_duplicate'] = sample['is_duplicate']

In [25]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
204878,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
65972,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
131332,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249555,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101294,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184009,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
397317,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
267552,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41791,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
351221,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(temp_df.iloc[:,0:-1].values, temp_df.iloc[:,-1].values, test_size=0.2, random_state=42)

In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


rf = RandomForestClassifier()
rf.fit(X_train,y_train)
model = rf.predict(X_test)

print(accuracy_score(model,y_test))

0.749